name: ci
on: push
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Set Current Date
        run: echo "::set-output name=date::$(date + '%Y-%m-%d')"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with: 
            node-version: '20'
      - name: Package Installation
        run: npm install
      # - name: Lint
      #   run: npm run lint:frontend
      - name: Test
        uses: cypress-io/github-action@v6.1.0
        with:
          start: npm run dev:frontend
          project: ./client
          browser: chrome
      - name: Build
        run: npm run build:frontend
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4.0.0
        with:
          name: frontend-${{ steps.date.output.date }}
          path: ./client/dist
